site:
  title: strongSwan Documentation
  url: https://docs.strongswan.org
  start_page: 5.9@strongswan-docs::index.adoc
  robots: allow
content:
  sources:
  - url: https://github.com/strongswan/strongswan-docs.git
    branches: [antora]
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: css/site-extra.css
    contents: ./supplemental-ui/css/site-extra.css
  - path: partials/head-meta.hbs
    contents: ./supplemental-ui/partials/head-meta.hbs
  - path: partials/header-content.hbs
    contents: ./supplemental-ui/partials/header-content.hbs
  - path: partials/footer-content.hbs
    contents: ./supplemental-ui/partials/footer-content.hbs
  - path: img/strongswan.png
    contents: ./supplemental-ui/img/strongswan.png
  - path: favicon.ico
    contents: ./supplemental-ui/favicon.ico
  - path: ui.yml
    contents: |
      static_files:
      - favicon.ico
  # might not be necessary in the future
  - path: css/search.css
    contents: ./node_modules/@antora/lunr-extension/supplemental_ui/css/search.css
  - path: js/search-ui.js
    contents: ./node_modules/@antora/lunr-extension/supplemental_ui/js/search-ui.js
antora:
  extensions:
    - require: '@antora/lunr-extension'
asciidoc:
  attributes:
    page-pagination: true
